# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCount',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordVideoId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256)),
                ('path', models.CharField(max_length=1024)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('import_date', models.DateField(auto_now=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('watch_count', models.PositiveIntegerField(default=0)),
                ('last_watch_date', models.DateField(default=None, null=True)),
                ('rating', models.PositiveIntegerField(choices=[(0, 'G: For general audiences'), (1, 'PG: Parental guidance'), (2, 'PG13: Parents Strongly Cautioned'), (3, 'R: Restricted'), (4, 'NC17: NO ONE AND UNDER 17 ADMITTED'), (5, 'Private: Videos for private access')], default=5)),
            ],
        ),
        migrations.AddField(
            model_name='keywordvideoid',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.Video'),
        ),
    ]
