# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'video', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCount',
            fields=[
                ('keyword', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordVideoId',
            fields=[
                ('keyword', models.CharField(max_length=100)),
                ('video_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256)),
                ('path', models.CharField(max_length=1024)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('import_date', models.DateField(auto_now=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('watch_count', models.PositiveIntegerField(default=0)),
                ('last_watch_date', models.DateField(default=None, null=True)),
                ('rating', models.CharField(choices=[('G', 'For general audiences'), ('PG', 'Parental guidance'), ('PG13', 'Parents Strongly Cautioned'), ('R', 'Restricted'), ('NC17', 'NO ONE AND UNDER 17 ADMITTED')], default='R', max_length=4)),
            ],
        ),
    ]
