# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KeywordPathHash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('path_hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('path_hash', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=256)),
                ('path', models.CharField(max_length=1024)),
                ('duration', models.PositiveSmallIntegerField(null=True)),
                ('import_date', models.DateField(auto_now=True, null=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('watch_count', models.PositiveIntegerField(default=0)),
                ('last_watch_date', models.DateField(default=None, null=True)),
            ],
        ),
    ]
