# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordcount',
            name='id',
        ),
        migrations.AlterField(
            model_name='keywordcount',
            name='keyword',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
