# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-08 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_auto_20170307_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='need_convert',
            field=models.BooleanField(default=False),
        ),
    ]
