# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_need_convert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordvideoid',
            name='id',
        ),
        migrations.AlterField(
            model_name='keywordvideoid',
            name='video_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
