# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-07 02:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_auto_20170313_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='need_convert',
        ),
    ]
