# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_remove_video_need_convert'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='rating',
            field=models.IntegerField(default=17),
        ),
    ]
